grafana:
  ingress:
    enabled: true
  plugins: ["jdbranham-diagram-panel"]

prometheus:
  ingress:
    enabled: true
  prometheusSpec:
    # Get rules from everyone
    ruleSelector: &default-selector
      matchExpressions:
        - key: app
          operator: Exists
    serviceMonitorSelector: *default-selector
    podMonitorSelector:     *default-selector
