graph TD
  subgraph master
    kubernetes-dashboard -.-> kube-apiserver
    kube-apiserver -.-> kube-scheduler
    kube-apiserver -.-> kube-controller-manager
  end
  subgraph monitoring
    prometheus-operator -.-> kube-apiserver
    prometheus-operator -.-> prometheus
    prometheus -.-> alertmanager
    grafana -.-> prometheus
  end
