graph TD
  subgraph master
    kubernetes-dashboard -.-> apiserver
    apiserver -.-> kube-scheduler
    apiserver -.-> kube-controller-manager
  end
  subgraph monitoring
    prometheus-operator -.-> apiserver
    prometheus-operator -.-> prometheus
    prometheus -.-> alertmanager
    grafana -.-> prometheus
  end
