apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: google-fr
  labels:
    app: google
spec:
  endpoints:
    - interval: 30s
      metricRelabelings:
        - sourceLabels: ["__address__"]
          targetLabel: "__param_target"
        - sourceLabels: ["__param_target"]
          targetLabel: "instance"
        - replacement: "monitoring"
          targetLabel: "namespace"
        - replacement: "https://www.google.fr"
          targetLabel: "target"
        - replacement: "www.google.fr"
          targetLabel: "app"
      params:
        module:
          - http_2xx
        target:
          - https://www.google.fr
      path: "/probe"
      targetPort: 9115
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-blackbox-exporter
      app.kubernetes.io/instance: blackbox
